# Generated by Django 5.0.2 on 2024-02-18 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://alcaratello.com/wp-content/uploads/2021/03/meal-placeholder.jpg', max_length=500),
        ),
    ]
